PATH_TOOLS=../tools
include $(PATH_TOOLS)/esp32.mk

# Puede cambiar el valor de alguna variable
# debe descomentar aquel que quiera modificar
# para que funcione el cambio

# BAUD?=115200 # Velocidad de la transmisión serial en baudios
SERIAL=/dev/ttyACM0
# SERIALMONITOR?=picocom # Monitor serial, ejemplo [picocom, minicom]
# BOARD=esp32 # SoC a usar
# DTS_OVERLAY=./boards/esp32.overlay # Configuración de la board

# Puede agregar más instrucciones desde aquí
